/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MailboxQueryResponseOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailboxQueryResponseOneOf2{}

// MailboxQueryResponseOneOf2 struct for MailboxQueryResponseOneOf2
type MailboxQueryResponseOneOf2 struct {
	Type interface{} `json:"type"`
}

type _MailboxQueryResponseOneOf2 MailboxQueryResponseOneOf2

// NewMailboxQueryResponseOneOf2 instantiates a new MailboxQueryResponseOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailboxQueryResponseOneOf2(type_ interface{}) *MailboxQueryResponseOneOf2 {
	this := MailboxQueryResponseOneOf2{}
	this.Type = type_
	return &this
}

// NewMailboxQueryResponseOneOf2WithDefaults instantiates a new MailboxQueryResponseOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailboxQueryResponseOneOf2WithDefaults() *MailboxQueryResponseOneOf2 {
	this := MailboxQueryResponseOneOf2{}
	return &this
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *MailboxQueryResponseOneOf2) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MailboxQueryResponseOneOf2) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MailboxQueryResponseOneOf2) SetType(v interface{}) {
	o.Type = v
}

func (o MailboxQueryResponseOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailboxQueryResponseOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

func (o *MailboxQueryResponseOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailboxQueryResponseOneOf2 := _MailboxQueryResponseOneOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMailboxQueryResponseOneOf2)

	if err != nil {
		return err
	}

	*o = MailboxQueryResponseOneOf2(varMailboxQueryResponseOneOf2)

	return err
}

type NullableMailboxQueryResponseOneOf2 struct {
	value *MailboxQueryResponseOneOf2
	isSet bool
}

func (v NullableMailboxQueryResponseOneOf2) Get() *MailboxQueryResponseOneOf2 {
	return v.value
}

func (v *NullableMailboxQueryResponseOneOf2) Set(val *MailboxQueryResponseOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableMailboxQueryResponseOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableMailboxQueryResponseOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailboxQueryResponseOneOf2(val *MailboxQueryResponseOneOf2) *NullableMailboxQueryResponseOneOf2 {
	return &NullableMailboxQueryResponseOneOf2{value: val, isSet: true}
}

func (v NullableMailboxQueryResponseOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailboxQueryResponseOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


