/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InstanceUnreachableError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceUnreachableError{}

// InstanceUnreachableError Instance cannot be reached
type InstanceUnreachableError struct {
	Type interface{} `json:"type"`
	Title interface{} `json:"title"`
	// HTTP status code
	Status int32 `json:"status"`
	Detail string `json:"detail"`
	// An address pointing to another DFMailbox instance
	Address string `json:"address"`
}

type _InstanceUnreachableError InstanceUnreachableError

// NewInstanceUnreachableError instantiates a new InstanceUnreachableError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceUnreachableError(type_ interface{}, title interface{}, status int32, detail string, address string) *InstanceUnreachableError {
	this := InstanceUnreachableError{}
	this.Type = type_
	this.Title = title
	this.Status = status
	this.Detail = detail
	this.Address = address
	return &this
}

// NewInstanceUnreachableErrorWithDefaults instantiates a new InstanceUnreachableError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceUnreachableErrorWithDefaults() *InstanceUnreachableError {
	this := InstanceUnreachableError{}
	return &this
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *InstanceUnreachableError) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceUnreachableError) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InstanceUnreachableError) SetType(v interface{}) {
	o.Type = v
}

// GetTitle returns the Title field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *InstanceUnreachableError) GetTitle() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceUnreachableError) GetTitleOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *InstanceUnreachableError) SetTitle(v interface{}) {
	o.Title = v
}

// GetStatus returns the Status field value
func (o *InstanceUnreachableError) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *InstanceUnreachableError) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *InstanceUnreachableError) SetStatus(v int32) {
	o.Status = v
}

// GetDetail returns the Detail field value
func (o *InstanceUnreachableError) GetDetail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Detail
}

// GetDetailOk returns a tuple with the Detail field value
// and a boolean to check if the value has been set.
func (o *InstanceUnreachableError) GetDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Detail, true
}

// SetDetail sets field value
func (o *InstanceUnreachableError) SetDetail(v string) {
	o.Detail = v
}

// GetAddress returns the Address field value
func (o *InstanceUnreachableError) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *InstanceUnreachableError) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *InstanceUnreachableError) SetAddress(v string) {
	o.Address = v
}

func (o InstanceUnreachableError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceUnreachableError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	toSerialize["status"] = o.Status
	toSerialize["detail"] = o.Detail
	toSerialize["address"] = o.Address
	return toSerialize, nil
}

func (o *InstanceUnreachableError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"title",
		"status",
		"detail",
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstanceUnreachableError := _InstanceUnreachableError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInstanceUnreachableError)

	if err != nil {
		return err
	}

	*o = InstanceUnreachableError(varInstanceUnreachableError)

	return err
}

type NullableInstanceUnreachableError struct {
	value *InstanceUnreachableError
	isSet bool
}

func (v NullableInstanceUnreachableError) Get() *InstanceUnreachableError {
	return v.value
}

func (v *NullableInstanceUnreachableError) Set(val *InstanceUnreachableError) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceUnreachableError) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceUnreachableError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceUnreachableError(val *InstanceUnreachableError) *NullableInstanceUnreachableError {
	return &NullableInstanceUnreachableError{value: val, isSet: true}
}

func (v NullableInstanceUnreachableError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceUnreachableError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


