/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateInstance409ResponseOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateInstance409ResponseOneOf1{}

// UpdateInstance409ResponseOneOf1 struct for UpdateInstance409ResponseOneOf1
type UpdateInstance409ResponseOneOf1 struct {
	Error *string `json:"error,omitempty"`
}

// NewUpdateInstance409ResponseOneOf1 instantiates a new UpdateInstance409ResponseOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateInstance409ResponseOneOf1() *UpdateInstance409ResponseOneOf1 {
	this := UpdateInstance409ResponseOneOf1{}
	return &this
}

// NewUpdateInstance409ResponseOneOf1WithDefaults instantiates a new UpdateInstance409ResponseOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateInstance409ResponseOneOf1WithDefaults() *UpdateInstance409ResponseOneOf1 {
	this := UpdateInstance409ResponseOneOf1{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *UpdateInstance409ResponseOneOf1) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateInstance409ResponseOneOf1) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *UpdateInstance409ResponseOneOf1) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *UpdateInstance409ResponseOneOf1) SetError(v string) {
	o.Error = &v
}

func (o UpdateInstance409ResponseOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateInstance409ResponseOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableUpdateInstance409ResponseOneOf1 struct {
	value *UpdateInstance409ResponseOneOf1
	isSet bool
}

func (v NullableUpdateInstance409ResponseOneOf1) Get() *UpdateInstance409ResponseOneOf1 {
	return v.value
}

func (v *NullableUpdateInstance409ResponseOneOf1) Set(val *UpdateInstance409ResponseOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateInstance409ResponseOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateInstance409ResponseOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateInstance409ResponseOneOf1(val *UpdateInstance409ResponseOneOf1) *NullableUpdateInstance409ResponseOneOf1 {
	return &NullableUpdateInstance409ResponseOneOf1{value: val, isSet: true}
}

func (v NullableUpdateInstance409ResponseOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateInstance409ResponseOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


