/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MailboxQueryResponseOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailboxQueryResponseOneOf{}

// MailboxQueryResponseOneOf struct for MailboxQueryResponseOneOf
type MailboxQueryResponseOneOf struct {
	Type interface{} `json:"type"`
	Result FetchMailboxResult `json:"result"`
}

type _MailboxQueryResponseOneOf MailboxQueryResponseOneOf

// NewMailboxQueryResponseOneOf instantiates a new MailboxQueryResponseOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailboxQueryResponseOneOf(type_ interface{}, result FetchMailboxResult) *MailboxQueryResponseOneOf {
	this := MailboxQueryResponseOneOf{}
	this.Type = type_
	this.Result = result
	return &this
}

// NewMailboxQueryResponseOneOfWithDefaults instantiates a new MailboxQueryResponseOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailboxQueryResponseOneOfWithDefaults() *MailboxQueryResponseOneOf {
	this := MailboxQueryResponseOneOf{}
	return &this
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *MailboxQueryResponseOneOf) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MailboxQueryResponseOneOf) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MailboxQueryResponseOneOf) SetType(v interface{}) {
	o.Type = v
}

// GetResult returns the Result field value
func (o *MailboxQueryResponseOneOf) GetResult() FetchMailboxResult {
	if o == nil {
		var ret FetchMailboxResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *MailboxQueryResponseOneOf) GetResultOk() (*FetchMailboxResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *MailboxQueryResponseOneOf) SetResult(v FetchMailboxResult) {
	o.Result = v
}

func (o MailboxQueryResponseOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailboxQueryResponseOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *MailboxQueryResponseOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailboxQueryResponseOneOf := _MailboxQueryResponseOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMailboxQueryResponseOneOf)

	if err != nil {
		return err
	}

	*o = MailboxQueryResponseOneOf(varMailboxQueryResponseOneOf)

	return err
}

type NullableMailboxQueryResponseOneOf struct {
	value *MailboxQueryResponseOneOf
	isSet bool
}

func (v NullableMailboxQueryResponseOneOf) Get() *MailboxQueryResponseOneOf {
	return v.value
}

func (v *NullableMailboxQueryResponseOneOf) Set(val *MailboxQueryResponseOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableMailboxQueryResponseOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableMailboxQueryResponseOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailboxQueryResponseOneOf(val *MailboxQueryResponseOneOf) *NullableMailboxQueryResponseOneOf {
	return &NullableMailboxQueryResponseOneOf{value: val, isSet: true}
}

func (v NullableMailboxQueryResponseOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailboxQueryResponseOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


