/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.6.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RefreshToken200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefreshToken200Response{}

// RefreshToken200Response struct for RefreshToken200Response
type RefreshToken200Response struct {
	IdentityToken string `json:"identity_token"`
}

type _RefreshToken200Response RefreshToken200Response

// NewRefreshToken200Response instantiates a new RefreshToken200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefreshToken200Response(identityToken string) *RefreshToken200Response {
	this := RefreshToken200Response{}
	this.IdentityToken = identityToken
	return &this
}

// NewRefreshToken200ResponseWithDefaults instantiates a new RefreshToken200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefreshToken200ResponseWithDefaults() *RefreshToken200Response {
	this := RefreshToken200Response{}
	return &this
}

// GetIdentityToken returns the IdentityToken field value
func (o *RefreshToken200Response) GetIdentityToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdentityToken
}

// GetIdentityTokenOk returns a tuple with the IdentityToken field value
// and a boolean to check if the value has been set.
func (o *RefreshToken200Response) GetIdentityTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdentityToken, true
}

// SetIdentityToken sets field value
func (o *RefreshToken200Response) SetIdentityToken(v string) {
	o.IdentityToken = v
}

func (o RefreshToken200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefreshToken200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identity_token"] = o.IdentityToken
	return toSerialize, nil
}

func (o *RefreshToken200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"identity_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRefreshToken200Response := _RefreshToken200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRefreshToken200Response)

	if err != nil {
		return err
	}

	*o = RefreshToken200Response(varRefreshToken200Response)

	return err
}

type NullableRefreshToken200Response struct {
	value *RefreshToken200Response
	isSet bool
}

func (v NullableRefreshToken200Response) Get() *RefreshToken200Response {
	return v.value
}

func (v *NullableRefreshToken200Response) Set(val *RefreshToken200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRefreshToken200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRefreshToken200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefreshToken200Response(val *RefreshToken200Response) *NullableRefreshToken200Response {
	return &NullableRefreshToken200Response{value: val, isSet: true}
}

func (v NullableRefreshToken200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefreshToken200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


