/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UntrustedPlotError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UntrustedPlotError{}

// UntrustedPlotError Plot is not trusted
type UntrustedPlotError struct {
	Type interface{} `json:"type"`
	Title interface{} `json:"title"`
	// HTTP status code
	Status int32 `json:"status"`
	Details string `json:"details"`
	// An id assigned by DiamondFire to identify a plot, this ID can be used in /plot <plot_id>
	PlotId int32 `json:"plot_id"`
}

type _UntrustedPlotError UntrustedPlotError

// NewUntrustedPlotError instantiates a new UntrustedPlotError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUntrustedPlotError(type_ interface{}, title interface{}, status int32, details string, plotId int32) *UntrustedPlotError {
	this := UntrustedPlotError{}
	this.Type = type_
	this.Title = title
	this.Status = status
	this.Details = details
	this.PlotId = plotId
	return &this
}

// NewUntrustedPlotErrorWithDefaults instantiates a new UntrustedPlotError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUntrustedPlotErrorWithDefaults() *UntrustedPlotError {
	this := UntrustedPlotError{}
	return &this
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *UntrustedPlotError) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UntrustedPlotError) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UntrustedPlotError) SetType(v interface{}) {
	o.Type = v
}

// GetTitle returns the Title field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *UntrustedPlotError) GetTitle() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UntrustedPlotError) GetTitleOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *UntrustedPlotError) SetTitle(v interface{}) {
	o.Title = v
}

// GetStatus returns the Status field value
func (o *UntrustedPlotError) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UntrustedPlotError) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UntrustedPlotError) SetStatus(v int32) {
	o.Status = v
}

// GetDetails returns the Details field value
func (o *UntrustedPlotError) GetDetails() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value
// and a boolean to check if the value has been set.
func (o *UntrustedPlotError) GetDetailsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Details, true
}

// SetDetails sets field value
func (o *UntrustedPlotError) SetDetails(v string) {
	o.Details = v
}

// GetPlotId returns the PlotId field value
func (o *UntrustedPlotError) GetPlotId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PlotId
}

// GetPlotIdOk returns a tuple with the PlotId field value
// and a boolean to check if the value has been set.
func (o *UntrustedPlotError) GetPlotIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlotId, true
}

// SetPlotId sets field value
func (o *UntrustedPlotError) SetPlotId(v int32) {
	o.PlotId = v
}

func (o UntrustedPlotError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UntrustedPlotError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	toSerialize["status"] = o.Status
	toSerialize["details"] = o.Details
	toSerialize["plot_id"] = o.PlotId
	return toSerialize, nil
}

func (o *UntrustedPlotError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"title",
		"status",
		"details",
		"plot_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUntrustedPlotError := _UntrustedPlotError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUntrustedPlotError)

	if err != nil {
		return err
	}

	*o = UntrustedPlotError(varUntrustedPlotError)

	return err
}

type NullableUntrustedPlotError struct {
	value *UntrustedPlotError
	isSet bool
}

func (v NullableUntrustedPlotError) Get() *UntrustedPlotError {
	return v.value
}

func (v *NullableUntrustedPlotError) Set(val *UntrustedPlotError) {
	v.value = val
	v.isSet = true
}

func (v NullableUntrustedPlotError) IsSet() bool {
	return v.isSet
}

func (v *NullableUntrustedPlotError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUntrustedPlotError(val *UntrustedPlotError) *NullableUntrustedPlotError {
	return &NullableUntrustedPlotError{value: val, isSet: true}
}

func (v NullableUntrustedPlotError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUntrustedPlotError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


