/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UnregisteredPlotError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnregisteredPlotError{}

// UnregisteredPlotError Plot not registered
type UnregisteredPlotError struct {
	Type interface{} `json:"type"`
	Title interface{} `json:"title"`
	// HTTP status code
	Status int32 `json:"status"`
	Details string `json:"details"`
	// An id assigned by DiamondFire to identify a plot, this ID can be used in /plot <plot_id>
	PlotId int32 `json:"plot_id"`
}

type _UnregisteredPlotError UnregisteredPlotError

// NewUnregisteredPlotError instantiates a new UnregisteredPlotError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnregisteredPlotError(type_ interface{}, title interface{}, status int32, details string, plotId int32) *UnregisteredPlotError {
	this := UnregisteredPlotError{}
	this.Type = type_
	this.Title = title
	this.Status = status
	this.Details = details
	this.PlotId = plotId
	return &this
}

// NewUnregisteredPlotErrorWithDefaults instantiates a new UnregisteredPlotError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnregisteredPlotErrorWithDefaults() *UnregisteredPlotError {
	this := UnregisteredPlotError{}
	return &this
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *UnregisteredPlotError) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnregisteredPlotError) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UnregisteredPlotError) SetType(v interface{}) {
	o.Type = v
}

// GetTitle returns the Title field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *UnregisteredPlotError) GetTitle() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnregisteredPlotError) GetTitleOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *UnregisteredPlotError) SetTitle(v interface{}) {
	o.Title = v
}

// GetStatus returns the Status field value
func (o *UnregisteredPlotError) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UnregisteredPlotError) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UnregisteredPlotError) SetStatus(v int32) {
	o.Status = v
}

// GetDetails returns the Details field value
func (o *UnregisteredPlotError) GetDetails() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value
// and a boolean to check if the value has been set.
func (o *UnregisteredPlotError) GetDetailsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Details, true
}

// SetDetails sets field value
func (o *UnregisteredPlotError) SetDetails(v string) {
	o.Details = v
}

// GetPlotId returns the PlotId field value
func (o *UnregisteredPlotError) GetPlotId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PlotId
}

// GetPlotIdOk returns a tuple with the PlotId field value
// and a boolean to check if the value has been set.
func (o *UnregisteredPlotError) GetPlotIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlotId, true
}

// SetPlotId sets field value
func (o *UnregisteredPlotError) SetPlotId(v int32) {
	o.PlotId = v
}

func (o UnregisteredPlotError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnregisteredPlotError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	toSerialize["status"] = o.Status
	toSerialize["details"] = o.Details
	toSerialize["plot_id"] = o.PlotId
	return toSerialize, nil
}

func (o *UnregisteredPlotError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"title",
		"status",
		"details",
		"plot_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnregisteredPlotError := _UnregisteredPlotError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUnregisteredPlotError)

	if err != nil {
		return err
	}

	*o = UnregisteredPlotError(varUnregisteredPlotError)

	return err
}

type NullableUnregisteredPlotError struct {
	value *UnregisteredPlotError
	isSet bool
}

func (v NullableUnregisteredPlotError) Get() *UnregisteredPlotError {
	return v.value
}

func (v *NullableUnregisteredPlotError) Set(val *UnregisteredPlotError) {
	v.value = val
	v.isSet = true
}

func (v NullableUnregisteredPlotError) IsSet() bool {
	return v.isSet
}

func (v *NullableUnregisteredPlotError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnregisteredPlotError(val *UnregisteredPlotError) *NullableUnregisteredPlotError {
	return &NullableUnregisteredPlotError{value: val, isSet: true}
}

func (v NullableUnregisteredPlotError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnregisteredPlotError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


