/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UnregisteredPlotsError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnregisteredPlotsError{}

// UnregisteredPlotsError Some plots are not registered
type UnregisteredPlotsError struct {
	Type interface{} `json:"type"`
	Title interface{} `json:"title"`
	// HTTP status code
	Status int32 `json:"status"`
	Detail string `json:"detail"`
	PlotIds interface{} `json:"plot_ids"`
}

type _UnregisteredPlotsError UnregisteredPlotsError

// NewUnregisteredPlotsError instantiates a new UnregisteredPlotsError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnregisteredPlotsError(type_ interface{}, title interface{}, status int32, detail string, plotIds interface{}) *UnregisteredPlotsError {
	this := UnregisteredPlotsError{}
	this.Type = type_
	this.Title = title
	this.Status = status
	this.Detail = detail
	this.PlotIds = plotIds
	return &this
}

// NewUnregisteredPlotsErrorWithDefaults instantiates a new UnregisteredPlotsError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnregisteredPlotsErrorWithDefaults() *UnregisteredPlotsError {
	this := UnregisteredPlotsError{}
	return &this
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *UnregisteredPlotsError) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnregisteredPlotsError) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UnregisteredPlotsError) SetType(v interface{}) {
	o.Type = v
}

// GetTitle returns the Title field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *UnregisteredPlotsError) GetTitle() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnregisteredPlotsError) GetTitleOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *UnregisteredPlotsError) SetTitle(v interface{}) {
	o.Title = v
}

// GetStatus returns the Status field value
func (o *UnregisteredPlotsError) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UnregisteredPlotsError) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UnregisteredPlotsError) SetStatus(v int32) {
	o.Status = v
}

// GetDetail returns the Detail field value
func (o *UnregisteredPlotsError) GetDetail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Detail
}

// GetDetailOk returns a tuple with the Detail field value
// and a boolean to check if the value has been set.
func (o *UnregisteredPlotsError) GetDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Detail, true
}

// SetDetail sets field value
func (o *UnregisteredPlotsError) SetDetail(v string) {
	o.Detail = v
}

// GetPlotIds returns the PlotIds field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *UnregisteredPlotsError) GetPlotIds() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.PlotIds
}

// GetPlotIdsOk returns a tuple with the PlotIds field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnregisteredPlotsError) GetPlotIdsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.PlotIds) {
		return nil, false
	}
	return &o.PlotIds, true
}

// SetPlotIds sets field value
func (o *UnregisteredPlotsError) SetPlotIds(v interface{}) {
	o.PlotIds = v
}

func (o UnregisteredPlotsError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnregisteredPlotsError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	toSerialize["status"] = o.Status
	toSerialize["detail"] = o.Detail
	if o.PlotIds != nil {
		toSerialize["plot_ids"] = o.PlotIds
	}
	return toSerialize, nil
}

func (o *UnregisteredPlotsError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"title",
		"status",
		"detail",
		"plot_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnregisteredPlotsError := _UnregisteredPlotsError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUnregisteredPlotsError)

	if err != nil {
		return err
	}

	*o = UnregisteredPlotsError(varUnregisteredPlotsError)

	return err
}

type NullableUnregisteredPlotsError struct {
	value *UnregisteredPlotsError
	isSet bool
}

func (v NullableUnregisteredPlotsError) Get() *UnregisteredPlotsError {
	return v.value
}

func (v *NullableUnregisteredPlotsError) Set(val *UnregisteredPlotsError) {
	v.value = val
	v.isSet = true
}

func (v NullableUnregisteredPlotsError) IsSet() bool {
	return v.isSet
}

func (v *NullableUnregisteredPlotsError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnregisteredPlotsError(val *UnregisteredPlotsError) *NullableUnregisteredPlotsError {
	return &NullableUnregisteredPlotsError{value: val, isSet: true}
}

func (v NullableUnregisteredPlotsError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnregisteredPlotsError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


