/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CrossInstanceSendErrorOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CrossInstanceSendErrorOneOf1{}

// CrossInstanceSendErrorOneOf1 struct for CrossInstanceSendErrorOneOf1
type CrossInstanceSendErrorOneOf1 struct {
	Type interface{} `json:"type"`
	Title interface{} `json:"title"`
	// HTTP status code
	Status int32 `json:"status"`
	Details string `json:"details"`
	// An id assigned by DiamondFire to identify a plot, this ID can be used in /plot <plot_id>
	Sender int32 `json:"sender"`
	// A base64 URL encoded ed25519 public key
	ActualKey string `json:"actual_key"`
}

type _CrossInstanceSendErrorOneOf1 CrossInstanceSendErrorOneOf1

// NewCrossInstanceSendErrorOneOf1 instantiates a new CrossInstanceSendErrorOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCrossInstanceSendErrorOneOf1(type_ interface{}, title interface{}, status int32, details string, sender int32, actualKey string) *CrossInstanceSendErrorOneOf1 {
	this := CrossInstanceSendErrorOneOf1{}
	this.Type = type_
	this.Title = title
	this.Status = status
	this.Details = details
	this.Sender = sender
	this.ActualKey = actualKey
	return &this
}

// NewCrossInstanceSendErrorOneOf1WithDefaults instantiates a new CrossInstanceSendErrorOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCrossInstanceSendErrorOneOf1WithDefaults() *CrossInstanceSendErrorOneOf1 {
	this := CrossInstanceSendErrorOneOf1{}
	return &this
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *CrossInstanceSendErrorOneOf1) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CrossInstanceSendErrorOneOf1) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CrossInstanceSendErrorOneOf1) SetType(v interface{}) {
	o.Type = v
}

// GetTitle returns the Title field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *CrossInstanceSendErrorOneOf1) GetTitle() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CrossInstanceSendErrorOneOf1) GetTitleOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *CrossInstanceSendErrorOneOf1) SetTitle(v interface{}) {
	o.Title = v
}

// GetStatus returns the Status field value
func (o *CrossInstanceSendErrorOneOf1) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CrossInstanceSendErrorOneOf1) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CrossInstanceSendErrorOneOf1) SetStatus(v int32) {
	o.Status = v
}

// GetDetails returns the Details field value
func (o *CrossInstanceSendErrorOneOf1) GetDetails() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value
// and a boolean to check if the value has been set.
func (o *CrossInstanceSendErrorOneOf1) GetDetailsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Details, true
}

// SetDetails sets field value
func (o *CrossInstanceSendErrorOneOf1) SetDetails(v string) {
	o.Details = v
}

// GetSender returns the Sender field value
func (o *CrossInstanceSendErrorOneOf1) GetSender() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Sender
}

// GetSenderOk returns a tuple with the Sender field value
// and a boolean to check if the value has been set.
func (o *CrossInstanceSendErrorOneOf1) GetSenderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sender, true
}

// SetSender sets field value
func (o *CrossInstanceSendErrorOneOf1) SetSender(v int32) {
	o.Sender = v
}

// GetActualKey returns the ActualKey field value
func (o *CrossInstanceSendErrorOneOf1) GetActualKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ActualKey
}

// GetActualKeyOk returns a tuple with the ActualKey field value
// and a boolean to check if the value has been set.
func (o *CrossInstanceSendErrorOneOf1) GetActualKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActualKey, true
}

// SetActualKey sets field value
func (o *CrossInstanceSendErrorOneOf1) SetActualKey(v string) {
	o.ActualKey = v
}

func (o CrossInstanceSendErrorOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CrossInstanceSendErrorOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	toSerialize["status"] = o.Status
	toSerialize["details"] = o.Details
	toSerialize["sender"] = o.Sender
	toSerialize["actual_key"] = o.ActualKey
	return toSerialize, nil
}

func (o *CrossInstanceSendErrorOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"title",
		"status",
		"details",
		"sender",
		"actual_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCrossInstanceSendErrorOneOf1 := _CrossInstanceSendErrorOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCrossInstanceSendErrorOneOf1)

	if err != nil {
		return err
	}

	*o = CrossInstanceSendErrorOneOf1(varCrossInstanceSendErrorOneOf1)

	return err
}

type NullableCrossInstanceSendErrorOneOf1 struct {
	value *CrossInstanceSendErrorOneOf1
	isSet bool
}

func (v NullableCrossInstanceSendErrorOneOf1) Get() *CrossInstanceSendErrorOneOf1 {
	return v.value
}

func (v *NullableCrossInstanceSendErrorOneOf1) Set(val *CrossInstanceSendErrorOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableCrossInstanceSendErrorOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableCrossInstanceSendErrorOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCrossInstanceSendErrorOneOf1(val *CrossInstanceSendErrorOneOf1) *NullableCrossInstanceSendErrorOneOf1 {
	return &NullableCrossInstanceSendErrorOneOf1{value: val, isSet: true}
}

func (v NullableCrossInstanceSendErrorOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCrossInstanceSendErrorOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


