/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.6.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MailboxQueryOperationOneOf3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailboxQueryOperationOneOf3{}

// MailboxQueryOperationOneOf3 Imitates
type MailboxQueryOperationOneOf3 struct {
	Type interface{} `json:"type"`
	// A mailbox item id that refers to an item in any mailbox
	BeforeAt int64 `json:"before_at"`
}

type _MailboxQueryOperationOneOf3 MailboxQueryOperationOneOf3

// NewMailboxQueryOperationOneOf3 instantiates a new MailboxQueryOperationOneOf3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailboxQueryOperationOneOf3(type_ interface{}, beforeAt int64) *MailboxQueryOperationOneOf3 {
	this := MailboxQueryOperationOneOf3{}
	this.Type = type_
	this.BeforeAt = beforeAt
	return &this
}

// NewMailboxQueryOperationOneOf3WithDefaults instantiates a new MailboxQueryOperationOneOf3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailboxQueryOperationOneOf3WithDefaults() *MailboxQueryOperationOneOf3 {
	this := MailboxQueryOperationOneOf3{}
	return &this
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *MailboxQueryOperationOneOf3) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MailboxQueryOperationOneOf3) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MailboxQueryOperationOneOf3) SetType(v interface{}) {
	o.Type = v
}

// GetBeforeAt returns the BeforeAt field value
func (o *MailboxQueryOperationOneOf3) GetBeforeAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.BeforeAt
}

// GetBeforeAtOk returns a tuple with the BeforeAt field value
// and a boolean to check if the value has been set.
func (o *MailboxQueryOperationOneOf3) GetBeforeAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BeforeAt, true
}

// SetBeforeAt sets field value
func (o *MailboxQueryOperationOneOf3) SetBeforeAt(v int64) {
	o.BeforeAt = v
}

func (o MailboxQueryOperationOneOf3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailboxQueryOperationOneOf3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	toSerialize["before_at"] = o.BeforeAt
	return toSerialize, nil
}

func (o *MailboxQueryOperationOneOf3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"before_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailboxQueryOperationOneOf3 := _MailboxQueryOperationOneOf3{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMailboxQueryOperationOneOf3)

	if err != nil {
		return err
	}

	*o = MailboxQueryOperationOneOf3(varMailboxQueryOperationOneOf3)

	return err
}

type NullableMailboxQueryOperationOneOf3 struct {
	value *MailboxQueryOperationOneOf3
	isSet bool
}

func (v NullableMailboxQueryOperationOneOf3) Get() *MailboxQueryOperationOneOf3 {
	return v.value
}

func (v *NullableMailboxQueryOperationOneOf3) Set(val *MailboxQueryOperationOneOf3) {
	v.value = val
	v.isSet = true
}

func (v NullableMailboxQueryOperationOneOf3) IsSet() bool {
	return v.isSet
}

func (v *NullableMailboxQueryOperationOneOf3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailboxQueryOperationOneOf3(val *MailboxQueryOperationOneOf3) *NullableMailboxQueryOperationOneOf3 {
	return &NullableMailboxQueryOperationOneOf3{value: val, isSet: true}
}

func (v NullableMailboxQueryOperationOneOf3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailboxQueryOperationOneOf3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


