/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.6.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MailboxQueryResponseOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailboxQueryResponseOneOf1{}

// MailboxQueryResponseOneOf1 struct for MailboxQueryResponseOneOf1
type MailboxQueryResponseOneOf1 struct {
	Type interface{} `json:"type"`
	// A mailbox item id that refers to an item in any mailbox
	MsgId int64 `json:"msg_id"`
}

type _MailboxQueryResponseOneOf1 MailboxQueryResponseOneOf1

// NewMailboxQueryResponseOneOf1 instantiates a new MailboxQueryResponseOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailboxQueryResponseOneOf1(type_ interface{}, msgId int64) *MailboxQueryResponseOneOf1 {
	this := MailboxQueryResponseOneOf1{}
	this.Type = type_
	this.MsgId = msgId
	return &this
}

// NewMailboxQueryResponseOneOf1WithDefaults instantiates a new MailboxQueryResponseOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailboxQueryResponseOneOf1WithDefaults() *MailboxQueryResponseOneOf1 {
	this := MailboxQueryResponseOneOf1{}
	return &this
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *MailboxQueryResponseOneOf1) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MailboxQueryResponseOneOf1) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MailboxQueryResponseOneOf1) SetType(v interface{}) {
	o.Type = v
}

// GetMsgId returns the MsgId field value
func (o *MailboxQueryResponseOneOf1) GetMsgId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MsgId
}

// GetMsgIdOk returns a tuple with the MsgId field value
// and a boolean to check if the value has been set.
func (o *MailboxQueryResponseOneOf1) GetMsgIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MsgId, true
}

// SetMsgId sets field value
func (o *MailboxQueryResponseOneOf1) SetMsgId(v int64) {
	o.MsgId = v
}

func (o MailboxQueryResponseOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailboxQueryResponseOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	toSerialize["msg_id"] = o.MsgId
	return toSerialize, nil
}

func (o *MailboxQueryResponseOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"msg_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailboxQueryResponseOneOf1 := _MailboxQueryResponseOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMailboxQueryResponseOneOf1)

	if err != nil {
		return err
	}

	*o = MailboxQueryResponseOneOf1(varMailboxQueryResponseOneOf1)

	return err
}

type NullableMailboxQueryResponseOneOf1 struct {
	value *MailboxQueryResponseOneOf1
	isSet bool
}

func (v NullableMailboxQueryResponseOneOf1) Get() *MailboxQueryResponseOneOf1 {
	return v.value
}

func (v *NullableMailboxQueryResponseOneOf1) Set(val *MailboxQueryResponseOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableMailboxQueryResponseOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableMailboxQueryResponseOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailboxQueryResponseOneOf1(val *MailboxQueryResponseOneOf1) *NullableMailboxQueryResponseOneOf1 {
	return &NullableMailboxQueryResponseOneOf1{value: val, isSet: true}
}

func (v NullableMailboxQueryResponseOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailboxQueryResponseOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


