/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RefreshTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefreshTokenRequest{}

// RefreshTokenRequest struct for RefreshTokenRequest
type RefreshTokenRequest struct {
	// A UUID (universally unique identifier)
	Challenge string `json:"challenge"`
	// A base64 encoded ed25519 signature
	Signature string `json:"signature"`
}

type _RefreshTokenRequest RefreshTokenRequest

// NewRefreshTokenRequest instantiates a new RefreshTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefreshTokenRequest(challenge string, signature string) *RefreshTokenRequest {
	this := RefreshTokenRequest{}
	this.Challenge = challenge
	this.Signature = signature
	return &this
}

// NewRefreshTokenRequestWithDefaults instantiates a new RefreshTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefreshTokenRequestWithDefaults() *RefreshTokenRequest {
	this := RefreshTokenRequest{}
	return &this
}

// GetChallenge returns the Challenge field value
func (o *RefreshTokenRequest) GetChallenge() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Challenge
}

// GetChallengeOk returns a tuple with the Challenge field value
// and a boolean to check if the value has been set.
func (o *RefreshTokenRequest) GetChallengeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Challenge, true
}

// SetChallenge sets field value
func (o *RefreshTokenRequest) SetChallenge(v string) {
	o.Challenge = v
}

// GetSignature returns the Signature field value
func (o *RefreshTokenRequest) GetSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value
// and a boolean to check if the value has been set.
func (o *RefreshTokenRequest) GetSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Signature, true
}

// SetSignature sets field value
func (o *RefreshTokenRequest) SetSignature(v string) {
	o.Signature = v
}

func (o RefreshTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefreshTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["challenge"] = o.Challenge
	toSerialize["signature"] = o.Signature
	return toSerialize, nil
}

func (o *RefreshTokenRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"challenge",
		"signature",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRefreshTokenRequest := _RefreshTokenRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRefreshTokenRequest)

	if err != nil {
		return err
	}

	*o = RefreshTokenRequest(varRefreshTokenRequest)

	return err
}

type NullableRefreshTokenRequest struct {
	value *RefreshTokenRequest
	isSet bool
}

func (v NullableRefreshTokenRequest) Get() *RefreshTokenRequest {
	return v.value
}

func (v *NullableRefreshTokenRequest) Set(val *RefreshTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRefreshTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRefreshTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefreshTokenRequest(val *RefreshTokenRequest) *NullableRefreshTokenRequest {
	return &NullableRefreshTokenRequest{value: val, isSet: true}
}

func (v NullableRefreshTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefreshTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


