/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UnregisterPlot409Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnregisterPlot409Response{}

// UnregisterPlot409Response struct for UnregisterPlot409Response
type UnregisterPlot409Response struct {
	Error string `json:"error"`
}

type _UnregisterPlot409Response UnregisterPlot409Response

// NewUnregisterPlot409Response instantiates a new UnregisterPlot409Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnregisterPlot409Response(error_ string) *UnregisterPlot409Response {
	this := UnregisterPlot409Response{}
	this.Error = error_
	return &this
}

// NewUnregisterPlot409ResponseWithDefaults instantiates a new UnregisterPlot409Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnregisterPlot409ResponseWithDefaults() *UnregisterPlot409Response {
	this := UnregisterPlot409Response{}
	return &this
}

// GetError returns the Error field value
func (o *UnregisterPlot409Response) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *UnregisterPlot409Response) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *UnregisterPlot409Response) SetError(v string) {
	o.Error = v
}

func (o UnregisterPlot409Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnregisterPlot409Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *UnregisterPlot409Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnregisterPlot409Response := _UnregisterPlot409Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUnregisterPlot409Response)

	if err != nil {
		return err
	}

	*o = UnregisterPlot409Response(varUnregisterPlot409Response)

	return err
}

type NullableUnregisterPlot409Response struct {
	value *UnregisterPlot409Response
	isSet bool
}

func (v NullableUnregisterPlot409Response) Get() *UnregisterPlot409Response {
	return v.value
}

func (v *NullableUnregisterPlot409Response) Set(val *UnregisterPlot409Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUnregisterPlot409Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUnregisterPlot409Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnregisterPlot409Response(val *UnregisterPlot409Response) *NullableUnregisterPlot409Response {
	return &NullableUnregisterPlot409Response{value: val, isSet: true}
}

func (v NullableUnregisterPlot409Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnregisterPlot409Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


