/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// MarkKeyAsCompromised400Response - struct for MarkKeyAsCompromised400Response
type MarkKeyAsCompromised400Response struct {
	ChallengeFailedError *ChallengeFailedError
	InvalidChallengeError *InvalidChallengeError
}

// ChallengeFailedErrorAsMarkKeyAsCompromised400Response is a convenience function that returns ChallengeFailedError wrapped in MarkKeyAsCompromised400Response
func ChallengeFailedErrorAsMarkKeyAsCompromised400Response(v *ChallengeFailedError) MarkKeyAsCompromised400Response {
	return MarkKeyAsCompromised400Response{
		ChallengeFailedError: v,
	}
}

// InvalidChallengeErrorAsMarkKeyAsCompromised400Response is a convenience function that returns InvalidChallengeError wrapped in MarkKeyAsCompromised400Response
func InvalidChallengeErrorAsMarkKeyAsCompromised400Response(v *InvalidChallengeError) MarkKeyAsCompromised400Response {
	return MarkKeyAsCompromised400Response{
		InvalidChallengeError: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *MarkKeyAsCompromised400Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ChallengeFailedError
	err = newStrictDecoder(data).Decode(&dst.ChallengeFailedError)
	if err == nil {
		jsonChallengeFailedError, _ := json.Marshal(dst.ChallengeFailedError)
		if string(jsonChallengeFailedError) == "{}" { // empty struct
			dst.ChallengeFailedError = nil
		} else {
			if err = validator.Validate(dst.ChallengeFailedError); err != nil {
				dst.ChallengeFailedError = nil
			} else {
				match++
			}
		}
	} else {
		dst.ChallengeFailedError = nil
	}

	// try to unmarshal data into InvalidChallengeError
	err = newStrictDecoder(data).Decode(&dst.InvalidChallengeError)
	if err == nil {
		jsonInvalidChallengeError, _ := json.Marshal(dst.InvalidChallengeError)
		if string(jsonInvalidChallengeError) == "{}" { // empty struct
			dst.InvalidChallengeError = nil
		} else {
			if err = validator.Validate(dst.InvalidChallengeError); err != nil {
				dst.InvalidChallengeError = nil
			} else {
				match++
			}
		}
	} else {
		dst.InvalidChallengeError = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ChallengeFailedError = nil
		dst.InvalidChallengeError = nil

		return fmt.Errorf("data matches more than one schema in oneOf(MarkKeyAsCompromised400Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(MarkKeyAsCompromised400Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src MarkKeyAsCompromised400Response) MarshalJSON() ([]byte, error) {
	if src.ChallengeFailedError != nil {
		return json.Marshal(&src.ChallengeFailedError)
	}

	if src.InvalidChallengeError != nil {
		return json.Marshal(&src.InvalidChallengeError)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *MarkKeyAsCompromised400Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ChallengeFailedError != nil {
		return obj.ChallengeFailedError
	}

	if obj.InvalidChallengeError != nil {
		return obj.InvalidChallengeError
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj MarkKeyAsCompromised400Response) GetActualInstanceValue() (interface{}) {
	if obj.ChallengeFailedError != nil {
		return *obj.ChallengeFailedError
	}

	if obj.InvalidChallengeError != nil {
		return *obj.InvalidChallengeError
	}

	// all schemas are nil
	return nil
}

type NullableMarkKeyAsCompromised400Response struct {
	value *MarkKeyAsCompromised400Response
	isSet bool
}

func (v NullableMarkKeyAsCompromised400Response) Get() *MarkKeyAsCompromised400Response {
	return v.value
}

func (v *NullableMarkKeyAsCompromised400Response) Set(val *MarkKeyAsCompromised400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableMarkKeyAsCompromised400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableMarkKeyAsCompromised400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarkKeyAsCompromised400Response(val *MarkKeyAsCompromised400Response) *NullableMarkKeyAsCompromised400Response {
	return &NullableMarkKeyAsCompromised400Response{value: val, isSet: true}
}

func (v NullableMarkKeyAsCompromised400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarkKeyAsCompromised400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


