/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LookupInstanceAddress200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LookupInstanceAddress200Response{}

// LookupInstanceAddress200Response struct for LookupInstanceAddress200Response
type LookupInstanceAddress200Response struct {
	// An address pointing to another DFMailbox instance
	Address string `json:"address"`
}

type _LookupInstanceAddress200Response LookupInstanceAddress200Response

// NewLookupInstanceAddress200Response instantiates a new LookupInstanceAddress200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLookupInstanceAddress200Response(address string) *LookupInstanceAddress200Response {
	this := LookupInstanceAddress200Response{}
	this.Address = address
	return &this
}

// NewLookupInstanceAddress200ResponseWithDefaults instantiates a new LookupInstanceAddress200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLookupInstanceAddress200ResponseWithDefaults() *LookupInstanceAddress200Response {
	this := LookupInstanceAddress200Response{}
	return &this
}

// GetAddress returns the Address field value
func (o *LookupInstanceAddress200Response) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *LookupInstanceAddress200Response) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *LookupInstanceAddress200Response) SetAddress(v string) {
	o.Address = v
}

func (o LookupInstanceAddress200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LookupInstanceAddress200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	return toSerialize, nil
}

func (o *LookupInstanceAddress200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLookupInstanceAddress200Response := _LookupInstanceAddress200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLookupInstanceAddress200Response)

	if err != nil {
		return err
	}

	*o = LookupInstanceAddress200Response(varLookupInstanceAddress200Response)

	return err
}

type NullableLookupInstanceAddress200Response struct {
	value *LookupInstanceAddress200Response
	isSet bool
}

func (v NullableLookupInstanceAddress200Response) Get() *LookupInstanceAddress200Response {
	return v.value
}

func (v *NullableLookupInstanceAddress200Response) Set(val *LookupInstanceAddress200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableLookupInstanceAddress200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableLookupInstanceAddress200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLookupInstanceAddress200Response(val *LookupInstanceAddress200Response) *NullableLookupInstanceAddress200Response {
	return &NullableLookupInstanceAddress200Response{value: val, isSet: true}
}

func (v NullableLookupInstanceAddress200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLookupInstanceAddress200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


