/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.6.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InlineObject5OneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InlineObject5OneOf{}

// InlineObject5OneOf struct for InlineObject5OneOf
type InlineObject5OneOf struct {
	Type interface{} `json:"type"`
	Title interface{} `json:"title"`
	// HTTP status code
	Status int32 `json:"status"`
	Detail string `json:"detail"`
	// An address pointing to another DFMailbox instance
	ExpectedAddress string `json:"expected_address"`
	// An address pointing to another DFMailbox instance
	ActualAddress string `json:"actual_address"`
}

type _InlineObject5OneOf InlineObject5OneOf

// NewInlineObject5OneOf instantiates a new InlineObject5OneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject5OneOf(type_ interface{}, title interface{}, status int32, detail string, expectedAddress string, actualAddress string) *InlineObject5OneOf {
	this := InlineObject5OneOf{}
	this.Type = type_
	this.Title = title
	this.Status = status
	this.Detail = detail
	this.ExpectedAddress = expectedAddress
	this.ActualAddress = actualAddress
	return &this
}

// NewInlineObject5OneOfWithDefaults instantiates a new InlineObject5OneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject5OneOfWithDefaults() *InlineObject5OneOf {
	this := InlineObject5OneOf{}
	return &this
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *InlineObject5OneOf) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InlineObject5OneOf) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InlineObject5OneOf) SetType(v interface{}) {
	o.Type = v
}

// GetTitle returns the Title field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *InlineObject5OneOf) GetTitle() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InlineObject5OneOf) GetTitleOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *InlineObject5OneOf) SetTitle(v interface{}) {
	o.Title = v
}

// GetStatus returns the Status field value
func (o *InlineObject5OneOf) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *InlineObject5OneOf) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *InlineObject5OneOf) SetStatus(v int32) {
	o.Status = v
}

// GetDetail returns the Detail field value
func (o *InlineObject5OneOf) GetDetail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Detail
}

// GetDetailOk returns a tuple with the Detail field value
// and a boolean to check if the value has been set.
func (o *InlineObject5OneOf) GetDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Detail, true
}

// SetDetail sets field value
func (o *InlineObject5OneOf) SetDetail(v string) {
	o.Detail = v
}

// GetExpectedAddress returns the ExpectedAddress field value
func (o *InlineObject5OneOf) GetExpectedAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpectedAddress
}

// GetExpectedAddressOk returns a tuple with the ExpectedAddress field value
// and a boolean to check if the value has been set.
func (o *InlineObject5OneOf) GetExpectedAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedAddress, true
}

// SetExpectedAddress sets field value
func (o *InlineObject5OneOf) SetExpectedAddress(v string) {
	o.ExpectedAddress = v
}

// GetActualAddress returns the ActualAddress field value
func (o *InlineObject5OneOf) GetActualAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ActualAddress
}

// GetActualAddressOk returns a tuple with the ActualAddress field value
// and a boolean to check if the value has been set.
func (o *InlineObject5OneOf) GetActualAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActualAddress, true
}

// SetActualAddress sets field value
func (o *InlineObject5OneOf) SetActualAddress(v string) {
	o.ActualAddress = v
}

func (o InlineObject5OneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InlineObject5OneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	toSerialize["status"] = o.Status
	toSerialize["detail"] = o.Detail
	toSerialize["expected_address"] = o.ExpectedAddress
	toSerialize["actual_address"] = o.ActualAddress
	return toSerialize, nil
}

func (o *InlineObject5OneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"title",
		"status",
		"detail",
		"expected_address",
		"actual_address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInlineObject5OneOf := _InlineObject5OneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInlineObject5OneOf)

	if err != nil {
		return err
	}

	*o = InlineObject5OneOf(varInlineObject5OneOf)

	return err
}

type NullableInlineObject5OneOf struct {
	value *InlineObject5OneOf
	isSet bool
}

func (v NullableInlineObject5OneOf) Get() *InlineObject5OneOf {
	return v.value
}

func (v *NullableInlineObject5OneOf) Set(val *InlineObject5OneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject5OneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject5OneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject5OneOf(val *InlineObject5OneOf) *NullableInlineObject5OneOf {
	return &NullableInlineObject5OneOf{value: val, isSet: true}
}

func (v NullableInlineObject5OneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject5OneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


