/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IntroduceInstance400ResponseOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntroduceInstance400ResponseOneOf1{}

// IntroduceInstance400ResponseOneOf1 struct for IntroduceInstance400ResponseOneOf1
type IntroduceInstance400ResponseOneOf1 struct {
	Error interface{} `json:"error"`
	// An address pointing to another DFMailbox instance
	ExpectedAddress string `json:"expected_address"`
}

type _IntroduceInstance400ResponseOneOf1 IntroduceInstance400ResponseOneOf1

// NewIntroduceInstance400ResponseOneOf1 instantiates a new IntroduceInstance400ResponseOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntroduceInstance400ResponseOneOf1(error_ interface{}, expectedAddress string) *IntroduceInstance400ResponseOneOf1 {
	this := IntroduceInstance400ResponseOneOf1{}
	this.Error = error_
	this.ExpectedAddress = expectedAddress
	return &this
}

// NewIntroduceInstance400ResponseOneOf1WithDefaults instantiates a new IntroduceInstance400ResponseOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntroduceInstance400ResponseOneOf1WithDefaults() *IntroduceInstance400ResponseOneOf1 {
	this := IntroduceInstance400ResponseOneOf1{}
	return &this
}

// GetError returns the Error field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *IntroduceInstance400ResponseOneOf1) GetError() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntroduceInstance400ResponseOneOf1) GetErrorOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *IntroduceInstance400ResponseOneOf1) SetError(v interface{}) {
	o.Error = v
}

// GetExpectedAddress returns the ExpectedAddress field value
func (o *IntroduceInstance400ResponseOneOf1) GetExpectedAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpectedAddress
}

// GetExpectedAddressOk returns a tuple with the ExpectedAddress field value
// and a boolean to check if the value has been set.
func (o *IntroduceInstance400ResponseOneOf1) GetExpectedAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedAddress, true
}

// SetExpectedAddress sets field value
func (o *IntroduceInstance400ResponseOneOf1) SetExpectedAddress(v string) {
	o.ExpectedAddress = v
}

func (o IntroduceInstance400ResponseOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntroduceInstance400ResponseOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	toSerialize["expected_address"] = o.ExpectedAddress
	return toSerialize, nil
}

func (o *IntroduceInstance400ResponseOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
		"expected_address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIntroduceInstance400ResponseOneOf1 := _IntroduceInstance400ResponseOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIntroduceInstance400ResponseOneOf1)

	if err != nil {
		return err
	}

	*o = IntroduceInstance400ResponseOneOf1(varIntroduceInstance400ResponseOneOf1)

	return err
}

type NullableIntroduceInstance400ResponseOneOf1 struct {
	value *IntroduceInstance400ResponseOneOf1
	isSet bool
}

func (v NullableIntroduceInstance400ResponseOneOf1) Get() *IntroduceInstance400ResponseOneOf1 {
	return v.value
}

func (v *NullableIntroduceInstance400ResponseOneOf1) Set(val *IntroduceInstance400ResponseOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableIntroduceInstance400ResponseOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableIntroduceInstance400ResponseOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntroduceInstance400ResponseOneOf1(val *IntroduceInstance400ResponseOneOf1) *NullableIntroduceInstance400ResponseOneOf1 {
	return &NullableIntroduceInstance400ResponseOneOf1{value: val, isSet: true}
}

func (v NullableIntroduceInstance400ResponseOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntroduceInstance400ResponseOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


