/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NonComplianceError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NonComplianceError{}

// NonComplianceError Shown when another instance isn't complying with the protocol
type NonComplianceError struct {
	Type interface{} `json:"type"`
	Title interface{} `json:"title"`
	// HTTP status code
	Status int32 `json:"status"`
	Detail string `json:"detail"`
}

type _NonComplianceError NonComplianceError

// NewNonComplianceError instantiates a new NonComplianceError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNonComplianceError(type_ interface{}, title interface{}, status int32, detail string) *NonComplianceError {
	this := NonComplianceError{}
	this.Type = type_
	this.Title = title
	this.Status = status
	this.Detail = detail
	return &this
}

// NewNonComplianceErrorWithDefaults instantiates a new NonComplianceError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNonComplianceErrorWithDefaults() *NonComplianceError {
	this := NonComplianceError{}
	return &this
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *NonComplianceError) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NonComplianceError) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NonComplianceError) SetType(v interface{}) {
	o.Type = v
}

// GetTitle returns the Title field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *NonComplianceError) GetTitle() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NonComplianceError) GetTitleOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *NonComplianceError) SetTitle(v interface{}) {
	o.Title = v
}

// GetStatus returns the Status field value
func (o *NonComplianceError) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *NonComplianceError) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *NonComplianceError) SetStatus(v int32) {
	o.Status = v
}

// GetDetail returns the Detail field value
func (o *NonComplianceError) GetDetail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Detail
}

// GetDetailOk returns a tuple with the Detail field value
// and a boolean to check if the value has been set.
func (o *NonComplianceError) GetDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Detail, true
}

// SetDetail sets field value
func (o *NonComplianceError) SetDetail(v string) {
	o.Detail = v
}

func (o NonComplianceError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NonComplianceError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	toSerialize["status"] = o.Status
	toSerialize["detail"] = o.Detail
	return toSerialize, nil
}

func (o *NonComplianceError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"title",
		"status",
		"detail",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNonComplianceError := _NonComplianceError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNonComplianceError)

	if err != nil {
		return err
	}

	*o = NonComplianceError(varNonComplianceError)

	return err
}

type NullableNonComplianceError struct {
	value *NonComplianceError
	isSet bool
}

func (v NullableNonComplianceError) Get() *NonComplianceError {
	return v.value
}

func (v *NullableNonComplianceError) Set(val *NonComplianceError) {
	v.value = val
	v.isSet = true
}

func (v NullableNonComplianceError) IsSet() bool {
	return v.isSet
}

func (v *NullableNonComplianceError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNonComplianceError(val *NonComplianceError) *NullableNonComplianceError {
	return &NullableNonComplianceError{value: val, isSet: true}
}

func (v NullableNonComplianceError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNonComplianceError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


