/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MarkKeyAsCompromised400ResponseOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MarkKeyAsCompromised400ResponseOneOf{}

// MarkKeyAsCompromised400ResponseOneOf struct for MarkKeyAsCompromised400ResponseOneOf
type MarkKeyAsCompromised400ResponseOneOf struct {
	Error interface{} `json:"error,omitempty"`
}

// NewMarkKeyAsCompromised400ResponseOneOf instantiates a new MarkKeyAsCompromised400ResponseOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarkKeyAsCompromised400ResponseOneOf() *MarkKeyAsCompromised400ResponseOneOf {
	this := MarkKeyAsCompromised400ResponseOneOf{}
	return &this
}

// NewMarkKeyAsCompromised400ResponseOneOfWithDefaults instantiates a new MarkKeyAsCompromised400ResponseOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarkKeyAsCompromised400ResponseOneOfWithDefaults() *MarkKeyAsCompromised400ResponseOneOf {
	this := MarkKeyAsCompromised400ResponseOneOf{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MarkKeyAsCompromised400ResponseOneOf) GetError() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MarkKeyAsCompromised400ResponseOneOf) GetErrorOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return &o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *MarkKeyAsCompromised400ResponseOneOf) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given interface{} and assigns it to the Error field.
func (o *MarkKeyAsCompromised400ResponseOneOf) SetError(v interface{}) {
	o.Error = v
}

func (o MarkKeyAsCompromised400ResponseOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MarkKeyAsCompromised400ResponseOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableMarkKeyAsCompromised400ResponseOneOf struct {
	value *MarkKeyAsCompromised400ResponseOneOf
	isSet bool
}

func (v NullableMarkKeyAsCompromised400ResponseOneOf) Get() *MarkKeyAsCompromised400ResponseOneOf {
	return v.value
}

func (v *NullableMarkKeyAsCompromised400ResponseOneOf) Set(val *MarkKeyAsCompromised400ResponseOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableMarkKeyAsCompromised400ResponseOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableMarkKeyAsCompromised400ResponseOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarkKeyAsCompromised400ResponseOneOf(val *MarkKeyAsCompromised400ResponseOneOf) *NullableMarkKeyAsCompromised400ResponseOneOf {
	return &NullableMarkKeyAsCompromised400ResponseOneOf{value: val, isSet: true}
}

func (v NullableMarkKeyAsCompromised400ResponseOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarkKeyAsCompromised400ResponseOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


