/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AlreadyExistsError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlreadyExistsError{}

// AlreadyExistsError This problem occurs when the resource being created is found to already exist on the server.
type AlreadyExistsError struct {
	Type interface{} `json:"type"`
	Title interface{} `json:"title"`
	Detail string `json:"detail"`
	// HTTP status code
	Status int32 `json:"status"`
}

type _AlreadyExistsError AlreadyExistsError

// NewAlreadyExistsError instantiates a new AlreadyExistsError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlreadyExistsError(type_ interface{}, title interface{}, detail string, status int32) *AlreadyExistsError {
	this := AlreadyExistsError{}
	this.Type = type_
	this.Title = title
	this.Detail = detail
	this.Status = status
	return &this
}

// NewAlreadyExistsErrorWithDefaults instantiates a new AlreadyExistsError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlreadyExistsErrorWithDefaults() *AlreadyExistsError {
	this := AlreadyExistsError{}
	return &this
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *AlreadyExistsError) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AlreadyExistsError) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AlreadyExistsError) SetType(v interface{}) {
	o.Type = v
}

// GetTitle returns the Title field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *AlreadyExistsError) GetTitle() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AlreadyExistsError) GetTitleOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *AlreadyExistsError) SetTitle(v interface{}) {
	o.Title = v
}

// GetDetail returns the Detail field value
func (o *AlreadyExistsError) GetDetail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Detail
}

// GetDetailOk returns a tuple with the Detail field value
// and a boolean to check if the value has been set.
func (o *AlreadyExistsError) GetDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Detail, true
}

// SetDetail sets field value
func (o *AlreadyExistsError) SetDetail(v string) {
	o.Detail = v
}

// GetStatus returns the Status field value
func (o *AlreadyExistsError) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AlreadyExistsError) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AlreadyExistsError) SetStatus(v int32) {
	o.Status = v
}

func (o AlreadyExistsError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlreadyExistsError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	toSerialize["detail"] = o.Detail
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *AlreadyExistsError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"title",
		"detail",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAlreadyExistsError := _AlreadyExistsError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAlreadyExistsError)

	if err != nil {
		return err
	}

	*o = AlreadyExistsError(varAlreadyExistsError)

	return err
}

type NullableAlreadyExistsError struct {
	value *AlreadyExistsError
	isSet bool
}

func (v NullableAlreadyExistsError) Get() *AlreadyExistsError {
	return v.value
}

func (v *NullableAlreadyExistsError) Set(val *AlreadyExistsError) {
	v.value = val
	v.isSet = true
}

func (v NullableAlreadyExistsError) IsSet() bool {
	return v.isSet
}

func (v *NullableAlreadyExistsError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlreadyExistsError(val *AlreadyExistsError) *NullableAlreadyExistsError {
	return &NullableAlreadyExistsError{value: val, isSet: true}
}

func (v NullableAlreadyExistsError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlreadyExistsError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


