/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.6.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InstanceKeyCompromisedError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceKeyCompromisedError{}

// InstanceKeyCompromisedError Instance key has been marked as compromised therefore being invalidated
type InstanceKeyCompromisedError struct {
	Type interface{} `json:"type"`
	Title interface{} `json:"title"`
	// HTTP status code
	Status int32 `json:"status"`
	Detail string `json:"detail"`
	// A base64 URL encoded ed25519 public key
	InstanceKey string `json:"instance_key"`
}

type _InstanceKeyCompromisedError InstanceKeyCompromisedError

// NewInstanceKeyCompromisedError instantiates a new InstanceKeyCompromisedError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceKeyCompromisedError(type_ interface{}, title interface{}, status int32, detail string, instanceKey string) *InstanceKeyCompromisedError {
	this := InstanceKeyCompromisedError{}
	this.Type = type_
	this.Title = title
	this.Status = status
	this.Detail = detail
	this.InstanceKey = instanceKey
	return &this
}

// NewInstanceKeyCompromisedErrorWithDefaults instantiates a new InstanceKeyCompromisedError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceKeyCompromisedErrorWithDefaults() *InstanceKeyCompromisedError {
	this := InstanceKeyCompromisedError{}
	return &this
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *InstanceKeyCompromisedError) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceKeyCompromisedError) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InstanceKeyCompromisedError) SetType(v interface{}) {
	o.Type = v
}

// GetTitle returns the Title field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *InstanceKeyCompromisedError) GetTitle() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceKeyCompromisedError) GetTitleOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *InstanceKeyCompromisedError) SetTitle(v interface{}) {
	o.Title = v
}

// GetStatus returns the Status field value
func (o *InstanceKeyCompromisedError) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *InstanceKeyCompromisedError) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *InstanceKeyCompromisedError) SetStatus(v int32) {
	o.Status = v
}

// GetDetail returns the Detail field value
func (o *InstanceKeyCompromisedError) GetDetail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Detail
}

// GetDetailOk returns a tuple with the Detail field value
// and a boolean to check if the value has been set.
func (o *InstanceKeyCompromisedError) GetDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Detail, true
}

// SetDetail sets field value
func (o *InstanceKeyCompromisedError) SetDetail(v string) {
	o.Detail = v
}

// GetInstanceKey returns the InstanceKey field value
func (o *InstanceKeyCompromisedError) GetInstanceKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstanceKey
}

// GetInstanceKeyOk returns a tuple with the InstanceKey field value
// and a boolean to check if the value has been set.
func (o *InstanceKeyCompromisedError) GetInstanceKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceKey, true
}

// SetInstanceKey sets field value
func (o *InstanceKeyCompromisedError) SetInstanceKey(v string) {
	o.InstanceKey = v
}

func (o InstanceKeyCompromisedError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceKeyCompromisedError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	toSerialize["status"] = o.Status
	toSerialize["detail"] = o.Detail
	toSerialize["instance_key"] = o.InstanceKey
	return toSerialize, nil
}

func (o *InstanceKeyCompromisedError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"title",
		"status",
		"detail",
		"instance_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstanceKeyCompromisedError := _InstanceKeyCompromisedError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInstanceKeyCompromisedError)

	if err != nil {
		return err
	}

	*o = InstanceKeyCompromisedError(varInstanceKeyCompromisedError)

	return err
}

type NullableInstanceKeyCompromisedError struct {
	value *InstanceKeyCompromisedError
	isSet bool
}

func (v NullableInstanceKeyCompromisedError) Get() *InstanceKeyCompromisedError {
	return v.value
}

func (v *NullableInstanceKeyCompromisedError) Set(val *InstanceKeyCompromisedError) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceKeyCompromisedError) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceKeyCompromisedError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceKeyCompromisedError(val *InstanceKeyCompromisedError) *NullableInstanceKeyCompromisedError {
	return &NullableInstanceKeyCompromisedError{value: val, isSet: true}
}

func (v NullableInstanceKeyCompromisedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceKeyCompromisedError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


