/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TrustPlots400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrustPlots400Response{}

// TrustPlots400Response struct for TrustPlots400Response
type TrustPlots400Response struct {
	Error interface{} `json:"error"`
}

type _TrustPlots400Response TrustPlots400Response

// NewTrustPlots400Response instantiates a new TrustPlots400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrustPlots400Response(error_ interface{}) *TrustPlots400Response {
	this := TrustPlots400Response{}
	this.Error = error_
	return &this
}

// NewTrustPlots400ResponseWithDefaults instantiates a new TrustPlots400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrustPlots400ResponseWithDefaults() *TrustPlots400Response {
	this := TrustPlots400Response{}
	return &this
}

// GetError returns the Error field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TrustPlots400Response) GetError() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrustPlots400Response) GetErrorOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *TrustPlots400Response) SetError(v interface{}) {
	o.Error = v
}

func (o TrustPlots400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrustPlots400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

func (o *TrustPlots400Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrustPlots400Response := _TrustPlots400Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrustPlots400Response)

	if err != nil {
		return err
	}

	*o = TrustPlots400Response(varTrustPlots400Response)

	return err
}

type NullableTrustPlots400Response struct {
	value *TrustPlots400Response
	isSet bool
}

func (v NullableTrustPlots400Response) Get() *TrustPlots400Response {
	return v.value
}

func (v *NullableTrustPlots400Response) Set(val *TrustPlots400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableTrustPlots400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableTrustPlots400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrustPlots400Response(val *TrustPlots400Response) *NullableTrustPlots400Response {
	return &NullableTrustPlots400Response{value: val, isSet: true}
}

func (v NullableTrustPlots400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrustPlots400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


