/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// CrossInstanceSendError - An error emitted when a cross instance send fails
type CrossInstanceSendError struct {
	CrossInstanceSendErrorOneOf *CrossInstanceSendErrorOneOf
	MarkKeyAsCompromised400ResponseOneOf *MarkKeyAsCompromised400ResponseOneOf
}

// CrossInstanceSendErrorOneOfAsCrossInstanceSendError is a convenience function that returns CrossInstanceSendErrorOneOf wrapped in CrossInstanceSendError
func CrossInstanceSendErrorOneOfAsCrossInstanceSendError(v *CrossInstanceSendErrorOneOf) CrossInstanceSendError {
	return CrossInstanceSendError{
		CrossInstanceSendErrorOneOf: v,
	}
}

// MarkKeyAsCompromised400ResponseOneOfAsCrossInstanceSendError is a convenience function that returns MarkKeyAsCompromised400ResponseOneOf wrapped in CrossInstanceSendError
func MarkKeyAsCompromised400ResponseOneOfAsCrossInstanceSendError(v *MarkKeyAsCompromised400ResponseOneOf) CrossInstanceSendError {
	return CrossInstanceSendError{
		MarkKeyAsCompromised400ResponseOneOf: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CrossInstanceSendError) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CrossInstanceSendErrorOneOf
	err = newStrictDecoder(data).Decode(&dst.CrossInstanceSendErrorOneOf)
	if err == nil {
		jsonCrossInstanceSendErrorOneOf, _ := json.Marshal(dst.CrossInstanceSendErrorOneOf)
		if string(jsonCrossInstanceSendErrorOneOf) == "{}" { // empty struct
			dst.CrossInstanceSendErrorOneOf = nil
		} else {
			if err = validator.Validate(dst.CrossInstanceSendErrorOneOf); err != nil {
				dst.CrossInstanceSendErrorOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.CrossInstanceSendErrorOneOf = nil
	}

	// try to unmarshal data into MarkKeyAsCompromised400ResponseOneOf
	err = newStrictDecoder(data).Decode(&dst.MarkKeyAsCompromised400ResponseOneOf)
	if err == nil {
		jsonMarkKeyAsCompromised400ResponseOneOf, _ := json.Marshal(dst.MarkKeyAsCompromised400ResponseOneOf)
		if string(jsonMarkKeyAsCompromised400ResponseOneOf) == "{}" { // empty struct
			dst.MarkKeyAsCompromised400ResponseOneOf = nil
		} else {
			if err = validator.Validate(dst.MarkKeyAsCompromised400ResponseOneOf); err != nil {
				dst.MarkKeyAsCompromised400ResponseOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.MarkKeyAsCompromised400ResponseOneOf = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CrossInstanceSendErrorOneOf = nil
		dst.MarkKeyAsCompromised400ResponseOneOf = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CrossInstanceSendError)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CrossInstanceSendError)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CrossInstanceSendError) MarshalJSON() ([]byte, error) {
	if src.CrossInstanceSendErrorOneOf != nil {
		return json.Marshal(&src.CrossInstanceSendErrorOneOf)
	}

	if src.MarkKeyAsCompromised400ResponseOneOf != nil {
		return json.Marshal(&src.MarkKeyAsCompromised400ResponseOneOf)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CrossInstanceSendError) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CrossInstanceSendErrorOneOf != nil {
		return obj.CrossInstanceSendErrorOneOf
	}

	if obj.MarkKeyAsCompromised400ResponseOneOf != nil {
		return obj.MarkKeyAsCompromised400ResponseOneOf
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CrossInstanceSendError) GetActualInstanceValue() (interface{}) {
	if obj.CrossInstanceSendErrorOneOf != nil {
		return *obj.CrossInstanceSendErrorOneOf
	}

	if obj.MarkKeyAsCompromised400ResponseOneOf != nil {
		return *obj.MarkKeyAsCompromised400ResponseOneOf
	}

	// all schemas are nil
	return nil
}

type NullableCrossInstanceSendError struct {
	value *CrossInstanceSendError
	isSet bool
}

func (v NullableCrossInstanceSendError) Get() *CrossInstanceSendError {
	return v.value
}

func (v *NullableCrossInstanceSendError) Set(val *CrossInstanceSendError) {
	v.value = val
	v.isSet = true
}

func (v NullableCrossInstanceSendError) IsSet() bool {
	return v.isSet
}

func (v *NullableCrossInstanceSendError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCrossInstanceSendError(val *CrossInstanceSendError) *NullableCrossInstanceSendError {
	return &NullableCrossInstanceSendError{value: val, isSet: true}
}

func (v NullableCrossInstanceSendError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCrossInstanceSendError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


