/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateInstance409ResponseOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateInstance409ResponseOneOf{}

// UpdateInstance409ResponseOneOf struct for UpdateInstance409ResponseOneOf
type UpdateInstance409ResponseOneOf struct {
	Error *string `json:"error,omitempty"`
}

// NewUpdateInstance409ResponseOneOf instantiates a new UpdateInstance409ResponseOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateInstance409ResponseOneOf() *UpdateInstance409ResponseOneOf {
	this := UpdateInstance409ResponseOneOf{}
	return &this
}

// NewUpdateInstance409ResponseOneOfWithDefaults instantiates a new UpdateInstance409ResponseOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateInstance409ResponseOneOfWithDefaults() *UpdateInstance409ResponseOneOf {
	this := UpdateInstance409ResponseOneOf{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *UpdateInstance409ResponseOneOf) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateInstance409ResponseOneOf) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *UpdateInstance409ResponseOneOf) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *UpdateInstance409ResponseOneOf) SetError(v string) {
	o.Error = &v
}

func (o UpdateInstance409ResponseOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateInstance409ResponseOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableUpdateInstance409ResponseOneOf struct {
	value *UpdateInstance409ResponseOneOf
	isSet bool
}

func (v NullableUpdateInstance409ResponseOneOf) Get() *UpdateInstance409ResponseOneOf {
	return v.value
}

func (v *NullableUpdateInstance409ResponseOneOf) Set(val *UpdateInstance409ResponseOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateInstance409ResponseOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateInstance409ResponseOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateInstance409ResponseOneOf(val *UpdateInstance409ResponseOneOf) *NullableUpdateInstance409ResponseOneOf {
	return &NullableUpdateInstance409ResponseOneOf{value: val, isSet: true}
}

func (v NullableUpdateInstance409ResponseOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateInstance409ResponseOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


