/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CrossSend200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CrossSend200Response{}

// CrossSend200Response struct for CrossSend200Response
type CrossSend200Response struct {
	// A mailbox item id that refers to an item in any mailbox
	MsgId int64 `json:"msg_id"`
}

type _CrossSend200Response CrossSend200Response

// NewCrossSend200Response instantiates a new CrossSend200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCrossSend200Response(msgId int64) *CrossSend200Response {
	this := CrossSend200Response{}
	this.MsgId = msgId
	return &this
}

// NewCrossSend200ResponseWithDefaults instantiates a new CrossSend200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCrossSend200ResponseWithDefaults() *CrossSend200Response {
	this := CrossSend200Response{}
	return &this
}

// GetMsgId returns the MsgId field value
func (o *CrossSend200Response) GetMsgId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MsgId
}

// GetMsgIdOk returns a tuple with the MsgId field value
// and a boolean to check if the value has been set.
func (o *CrossSend200Response) GetMsgIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MsgId, true
}

// SetMsgId sets field value
func (o *CrossSend200Response) SetMsgId(v int64) {
	o.MsgId = v
}

func (o CrossSend200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CrossSend200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["msg_id"] = o.MsgId
	return toSerialize, nil
}

func (o *CrossSend200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"msg_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCrossSend200Response := _CrossSend200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCrossSend200Response)

	if err != nil {
		return err
	}

	*o = CrossSend200Response(varCrossSend200Response)

	return err
}

type NullableCrossSend200Response struct {
	value *CrossSend200Response
	isSet bool
}

func (v NullableCrossSend200Response) Get() *CrossSend200Response {
	return v.value
}

func (v *NullableCrossSend200Response) Set(val *CrossSend200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCrossSend200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCrossSend200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCrossSend200Response(val *CrossSend200Response) *NullableCrossSend200Response {
	return &NullableCrossSend200Response{value: val, isSet: true}
}

func (v NullableCrossSend200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCrossSend200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


