/*
DFMailbox API

DFMailbox is a decentralized way to send messages to other DiamondFire plots.

API version: 0.6.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SendItemsErrorOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendItemsErrorOneOf2{}

// SendItemsErrorOneOf2 struct for SendItemsErrorOneOf2
type SendItemsErrorOneOf2 struct {
	Type interface{} `json:"type"`
	Title interface{} `json:"title"`
	// HTTP status code
	Status int32 `json:"status"`
	Detail string `json:"detail"`
	// An id assigned by DiamondFire to identify a plot, this ID can be used in /plot <plot_id>
	Receiver int32 `json:"receiver"`
}

type _SendItemsErrorOneOf2 SendItemsErrorOneOf2

// NewSendItemsErrorOneOf2 instantiates a new SendItemsErrorOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendItemsErrorOneOf2(type_ interface{}, title interface{}, status int32, detail string, receiver int32) *SendItemsErrorOneOf2 {
	this := SendItemsErrorOneOf2{}
	this.Type = type_
	this.Title = title
	this.Status = status
	this.Detail = detail
	this.Receiver = receiver
	return &this
}

// NewSendItemsErrorOneOf2WithDefaults instantiates a new SendItemsErrorOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendItemsErrorOneOf2WithDefaults() *SendItemsErrorOneOf2 {
	this := SendItemsErrorOneOf2{}
	return &this
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *SendItemsErrorOneOf2) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SendItemsErrorOneOf2) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SendItemsErrorOneOf2) SetType(v interface{}) {
	o.Type = v
}

// GetTitle returns the Title field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *SendItemsErrorOneOf2) GetTitle() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SendItemsErrorOneOf2) GetTitleOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *SendItemsErrorOneOf2) SetTitle(v interface{}) {
	o.Title = v
}

// GetStatus returns the Status field value
func (o *SendItemsErrorOneOf2) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SendItemsErrorOneOf2) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SendItemsErrorOneOf2) SetStatus(v int32) {
	o.Status = v
}

// GetDetail returns the Detail field value
func (o *SendItemsErrorOneOf2) GetDetail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Detail
}

// GetDetailOk returns a tuple with the Detail field value
// and a boolean to check if the value has been set.
func (o *SendItemsErrorOneOf2) GetDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Detail, true
}

// SetDetail sets field value
func (o *SendItemsErrorOneOf2) SetDetail(v string) {
	o.Detail = v
}

// GetReceiver returns the Receiver field value
func (o *SendItemsErrorOneOf2) GetReceiver() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Receiver
}

// GetReceiverOk returns a tuple with the Receiver field value
// and a boolean to check if the value has been set.
func (o *SendItemsErrorOneOf2) GetReceiverOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Receiver, true
}

// SetReceiver sets field value
func (o *SendItemsErrorOneOf2) SetReceiver(v int32) {
	o.Receiver = v
}

func (o SendItemsErrorOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendItemsErrorOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	toSerialize["status"] = o.Status
	toSerialize["detail"] = o.Detail
	toSerialize["receiver"] = o.Receiver
	return toSerialize, nil
}

func (o *SendItemsErrorOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"title",
		"status",
		"detail",
		"receiver",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendItemsErrorOneOf2 := _SendItemsErrorOneOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendItemsErrorOneOf2)

	if err != nil {
		return err
	}

	*o = SendItemsErrorOneOf2(varSendItemsErrorOneOf2)

	return err
}

type NullableSendItemsErrorOneOf2 struct {
	value *SendItemsErrorOneOf2
	isSet bool
}

func (v NullableSendItemsErrorOneOf2) Get() *SendItemsErrorOneOf2 {
	return v.value
}

func (v *NullableSendItemsErrorOneOf2) Set(val *SendItemsErrorOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableSendItemsErrorOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableSendItemsErrorOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendItemsErrorOneOf2(val *SendItemsErrorOneOf2) *NullableSendItemsErrorOneOf2 {
	return &NullableSendItemsErrorOneOf2{value: val, isSet: true}
}

func (v NullableSendItemsErrorOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendItemsErrorOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


